class country:
	country = {
	'INDIA' : 'in',
	'UNITED ARAB EMIRATES' : 'ae',
	'ARGENTINA' : 'ar',
	'AUSTRIA' : 'at',
	'AUSTRALIA' : 'au',
	'BELGIUM' : 'be',
	'BULGARIA' : 'bg',
	'BRAZIL' : 'br',
	'CANADA' : 'ca',
	'SWITZERLAND' : 'ch',
	"PEOPLE'S REPUBLIC OF CHINA" : 'cn',
	'COLOMBIA' : 'co',
	'CUBA' : 'cu',
	'CZECH REPUBLIC' : 'cz',
	'GERMANY' : 'de',
	'EGYPT' : 'eg',
	'FRANCE' : 'fr',
	'UNITED KINGDOM' : 'gb',
	'HONG KONG' : 'hk',
	'HUNGARY' : 'hu',
	'INDONESIA' : 'id',
	'IRELAND' : 'ie',
	'ISRAEL' : 'il',
	'ITALY' : 'it',
	'JAPAN' : 'jp',
	'KOREA' : 'kr',
	'LITHUANIA' : 'lt',
	'LATVIA' : 'lv',
	'MOROCCO' : 'ma',
	'MEXICO' : 'mx',
	'MALAYSIA' : 'my',
	'NIGERIA' : 'ng',
	'NETHERLANDS' : 'nl',
	'NORWAY' : 'no',
	'NEW ZEALAND' : 'nz',
	'PHILIPPINES' : 'ph',
	'POLAND' : 'pl',
	'PORTUGAL' : 'pt',
	'ROMANIA' : 'ro',
	'SERBIA' : 'rs',
	'RUSSIA' : 'ru',
	'SAUDI ARABIA' : 'sa',
	'SWEDEN' : 'se',
	'SINGAPORE' : 'sg',
	'SLOVENIA' : 'si',
	'SLOVAKIA' : 'sk',
	'THAILAND' : 'th',
	'TURKEY' : 'tr',
	'TAIWAN' : 'tw',
	'UKRAINE' : 'ua',
	'UNITED STATES' : 'us',
	'VENEZUELA' : 've',
	'SOUTH AFRICA' : 'za'}

